import { RefObject, useEffect, useState } from "react";

export interface UsePageTrackingProps {
  containerRef: RefObject<HTMLDivElement | null>;
  scale: number;
  pagedJsPageCount: number;
}

export interface UsePageTrackingReturn {
  currentPage: number;
}

/**
 * usePageTracking - Current Page Tracking Hook
 * 
 * Governance: Tracks current page for navigation display in Preview
 * Responsibility: 
 *   1. Monitor scroll position in the Preview container
 *   2. Query .pagedjs_page elements generated by Paged.js
 *   3. Calculate which page is currently in view
 *   4. Update page indicator for user orientation
 * Role: Contributor (view state only)
 * 
 * Strategy:
 * - Queries .pagedjs_page elements generated by Paged.js
 * - Uses middle-of-page threshold for page transition
 * - Multiplies DOM measurements by scale factor to get visual positions
 * - Only source is Paged.js pages (old pagination system removed)
 * - Updates page indicator in header for user orientation
 * 
 * State: Session state (ephemeral scroll tracking)
 * 
 * @see Mylo Governance: Preview is authoritative for pagination
 */
export function usePageTracking({
  containerRef,
  scale,
  pagedJsPageCount,
}: UsePageTrackingProps): UsePageTrackingReturn {
  const [currentPage, setCurrentPage] = useState(1);

  /**
   * SCROLL TRACKING: Update current page indicator based on scroll position
   */
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const handleScroll = () => {
      const scrollTop = container.scrollTop;
      const pagedPages = container.querySelectorAll('.pagedjs_page');
      
      if (pagedPages.length > 0) {
        let currentPageNumber = 1;
        
        for (let i = 0; i < pagedPages.length; i++) {
          const page = pagedPages[i] as HTMLElement;
          const pageTop = page.offsetTop;
          const pageHeight = page.offsetHeight;
          
          // Apply scale factor to get visual (scaled) positions
          const scaledPageTop = pageTop * scale;
          const scaledPageHeight = pageHeight * scale;
          
          if (scrollTop >= scaledPageTop + scaledPageHeight / 2) {
            currentPageNumber = i + 1;
          } else {
            break;
          }
        }
        
        setCurrentPage(Math.min(Math.max(1, currentPageNumber), pagedJsPageCount));
        console.log('[Scroll Tracking] Current page:', currentPageNumber, '(scale:', scale, ')');
      }
    };

    container.addEventListener('scroll', handleScroll);
    return () => container.removeEventListener('scroll', handleScroll);
  }, [pagedJsPageCount, scale]);

  return {
    currentPage,
  };
}
